### ISSUE TITLE
Able to take items out of an inventory

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/GameBox#4]
So another player said it was possible to glitch the inventory - at least the cookieclicker one. He says if you exit "perfectly" the inventory stays open and you can take items.

Also, I've heard (haven't played with "GUIs" yet) that using InventoryHolder prevents issues with potential glitches like these.

**Comment by NiklasEi** [comment]
I just tested it and used 'esc' to close the game. After a few dozend tries I endet up with the Cookie Clicker items in my inventory. But in my case it were all ghost items: I couldn't place/use or throw them and as soon as I clicked on one in my inventory they all disappeared. It should be fixed with a simple inventory update. I'll fix it for the next update. 

Was your player able to use the items?

I haven't heard that about using custom InventoryHolder. If that has benefits over my system it would be an improvement for GameBox 2.

**Comment by RoboMWM** [comment]
Yea, he used the escape key, forgot to mention that. As for InventoryHolder - I haven't used it yet, but @LaxWasHere might be able to provide input.

He was able to use the items - he was able to craft the iron block into iron ingots, and he was wearing the villager head (I was in-game as well and saw him wearing it.).

**Comment by RoboMWM** [comment]
It appears the other times he's glitching it, the items are indeed ghost items. He also mentions that he's able to cause it to glitch after buying something.

**Comment by NiklasEi** [comment]
I have some exams upcoming so I can't really spend much time with this right now. I will debug and try to find out what happened that one time where he was able to use the items asap. The gost items should be fixed with a delayed inventory update.

Did you check for any errors or other suspicious console output when your player got the items?

**Comment by RoboMWM** [comment]
> Did you check for any errors or other suspicious console output when your player got the items?

I did not, as I was busy doing other things at that time. I'll take a look at the logs though.

> I have some exams upcoming so I can't really spend much time with this right now.

Understood, it's a position I'm commonly in as well. I'm not concerned about ghost items, so no need for a delayed inventory update IMO.

**Comment by NiklasEi** [comment]
Have there been any more problems with this? I still only encountered gost items.

I think we could close this in favour of a new issue to implement an InventoryHolder based system.

**Comment by RoboMWM** [comment]
Yea, no update on this. I still get ghost items as well.

I know with other "inventory-gui" plugins I've been able to take items (not ghost items) when either the server or my connection is lagging - but I myself have not made any GUI-type plugins (yet) so I'm not sure why this could happen. (I do know that there are many inventory-based events to look out for though, such as InventoryDragEvent).
